title: "Priyanjali Patel"
email: "priyanjalipatel@gmail.com"
description: >-
  Data Scientist | PhD in Astrophysics

# Site URL settings
url: "https://priyanjalipatel.github.io"
baseurl: "/portfolio"   # because repo is 'portfolio'

# Theme
theme: minima

# Show pages in header menu
header_pages:
  - about.md
  - projects.md
  - contact.md

# Author info
author:
  name: "Priyanjali Patel"
  email: "priyanjalipatel@gmail.com"

# Social links
social_links:
  github: https://github.com/priyanjalipatel
  linkedin: https://www.linkedin.com/in/priyanjalipatel
  kaggle: https://www.kaggle.com/priyanjalipatel
  scholar: https://scholar.google.com/citations?hl=en&user=Ola1DfwAAAAJ
  medium: https://medium.com/@priya_85674

# Exclude unnecessary files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
